org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Set the maximum number of workers to 4 to avoid overloading the machine.
org.gradle.workers.max=4
# Set the Kotlin compiler execution strategy to in-process to avoid "Could not
# connect to Kotlin compile daemon" error.
kotlin.compiler.execution.strategy=in-process
# Allow the google-services plugin to work even if the google-services.json is not present.
googleServices.missing.passthrough=true
